import {
	Activity,
	AlertCircle,
	AlignLeft,
	AlignRight,
	AlignCenter,
	AlignJustify,
	ArrowRight,
	BellDot,
	Bookmark,
	BookOpen,
	Boxes,
	CalendarClock,
	Check,
	CheckCircle2,
	CheckIcon,
	ChevronDown,
	ChevronDownIcon,
	ChevronRight,
	ChevronRightIcon,
	ChevronUpIcon,
	CircleIcon,
	Code,
	Cog,
	Command,
	Eye,
	EyeOff,
	Download,
	FileTextIcon,
	GripVerticalIcon,
	LocateIcon,
	Hash,
	Inbox,
	Info,
	Layers,
	LayoutDashboard,
	ListTree,
	Link2,
	Loader2,
	MapPin,
	MessageCircle,
	Lock,
	LockOpen,
	Moon,
	MoreHorizontal,
	Palette,
	PanelLeftIcon,
	PencilLine,
	PenLine,
	PenTool,
	Pin,
	Plus,
	Save,
	Search,
	SearchIcon,
	Sun,
	TagIcon,
	Target,
	Trash2,
	User,
	UserIcon,
	X,
	XCircleIcon,
	XIcon,
	LogOut,
	NotepadText,
	Star,
	ListOrdered,
	List,
	Bold,
	Italic,
	Underline,
	Subscript,
	Superscript,
	Strikethrough,
	Redo,
	Undo,
} from "lucide-react";

export const lucideIcons = {
	activity: Activity,
	alertCircle: AlertCircle,
	alignLeft: AlignLeft,
	alignRight: AlignRight,
	alignCenter: AlignCenter,
	alignJustify: AlignJustify,
	arrowRight: ArrowRight,
	bellDot: BellDot,
	bookmark: Bookmark,
	bookOpen: BookOpen,
	bold: Bold,
	italic: Italic,
	underline: Underline,
	subScript: Subscript,
	strikethrough: Strikethrough,
	superScript: Superscript,
	undo: Undo,
	redo: Redo,
	boxes: Boxes,
	calendarClock: CalendarClock,
	check: Check,
	checkCircle2: CheckCircle2,
	checkIcon: CheckIcon,
	chevronDown: ChevronDown,
	chevronDownIcon: ChevronDownIcon,
	chevronRight: ChevronRight,
	chevronRightIcon: ChevronRightIcon,
	chevronUpIcon: ChevronUpIcon,
	circleIcon: CircleIcon,
	code: Code,
	command: Command,
	eye: Eye,
	eyeOff: EyeOff,
	export: Download,
	fileTextIcon: FileTextIcon,
	gripVerticalIcon: GripVerticalIcon,
	hash: Hash,
	inbox: Inbox,
	info: Info,
	layers: Layers,
	layoutDashboard: LayoutDashboard,
	list: List,
	listOrdered: ListOrdered,
	link2: Link2,
	listTree: ListTree,
	loader2: Loader2,
	locate: LocateIcon,
	lock: Lock,
	lockOpen: LockOpen,
	logOut: LogOut,
	mapPin: MapPin,
	messageCircle: MessageCircle,
	moon: Moon,
	moreHorizontal: MoreHorizontal,
	notePad: NotepadText,
	palette: Palette,
	panelLeftIcon: PanelLeftIcon,
	pencilLine: PencilLine,
	penTool: PenTool,
	penLine: PenLine,
	pin: Pin,
	plus: Plus,
	save: Save,
	schedule: CalendarClock,
	search: Search,
	searchIcon: SearchIcon,
	settings: Cog,
	sun: Sun,
	star: Star,
	tagIcon: TagIcon,
	target: Target,
	trash2: Trash2,
	user: User,
	userIcon: UserIcon,
	x: X,
	xCircleIcon: XCircleIcon,
	xIcon: XIcon,
};
