import {
	Activity,
	AlertCircle,
	Bookmark,
	BookOpen,
	Boxes,
	CalendarClock,
	Check,
	CheckCircle2,
	CheckIcon,
	ChevronDown,
	ChevronDownIcon,
	ChevronRight,
	ChevronRightIcon,
	ChevronUpIcon,
	CircleIcon,
	Code,
	Cog,
	Command,
	Eye,
	EyeOff,
	FileTextIcon,
	GripVerticalIcon,
	Hash,
	Inbox,
	Layers,
	LayoutDashboard,
	Loader2,
	Lock,
	LockOpen,
	Moon,
	MoreHorizontal,
	Palette,
	PanelLeftIcon,
	PenLine,
	PenTool,
	Plus,
	Save,
	Search,
	SearchIcon,
	Sun,
	TagIcon,
	Target,
	Trash2,
	User,
	UserIcon,
	X,
	XCircleIcon,
	XIcon,
	LogOut,
} from "lucide-react";

export const lucideIcons = {
	activity: Activity,
	alertCircle: AlertCircle,
	bookmark: Bookmark,
	bookOpen: BookOpen,
	boxes: Boxes,
	calendarClock: CalendarClock,
	check: Check,
	checkCircle2: CheckCircle2,
	checkIcon: CheckIcon,
	chevronDown: ChevronDown,
	chevronDownIcon: ChevronDownIcon,
	chevronRight: ChevronRight,
	chevronRightIcon: ChevronRightIcon,
	chevronUpIcon: ChevronUpIcon,
	circleIcon: CircleIcon,
	code: Code,
	command: Command,
	eye: Eye,
	eyeOff: EyeOff,
	fileTextIcon: FileTextIcon,
	gripVerticalIcon: GripVerticalIcon,
	hash: Hash,
	inbox: Inbox,
	layers: Layers,
	layoutDashboard: LayoutDashboard,
	loader2: Loader2,
	lock: Lock,
	lockOpen: LockOpen,
	logOut: LogOut,
	moon: Moon,
	moreHorizontal: MoreHorizontal,
	palette: Palette,
	panelLeftIcon: PanelLeftIcon,
	penTool: PenTool,
	penLine: PenLine,
	plus: Plus,
	save: Save,
	search: Search,
	searchIcon: SearchIcon,
	settings: Cog,
	sun: Sun,
	tagIcon: TagIcon,
	target: Target,
	trash2: Trash2,
	user: User,
	userIcon: UserIcon,
	x: X,
	xCircleIcon: XCircleIcon,
	xIcon: XIcon,
};
