name: Mirror main to public

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push main to org public repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/synapcity/synapcity-web.git
          git push public origin/main:refs/heads/main --force-with-lease
