name: Verify

on: [push, pull_request]

jobs:
  verify:
    name: Verify code
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run verify script
        run: npm run verify
