import { writeFileSync } from 'fs'
import { resolve } from 'path'

const SITE_URL = (process.env.SITE_URL ?? 'https://official-synapcity.vercel.app/').replace(/\/$/, '')

const pages = ['/', '/home', '/home/dashboards', '/home/notes']

const urls = pages
  .map((page) => `  <url><loc>${SITE_URL}${page}</loc></url>`)
  .join('\n')

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`

writeFileSync(resolve(process.cwd(), 'public', 'sitemap.xml'), sitemap)

const robots = `# Generated by scripts/generate-sitemap.ts\nUser-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`
writeFileSync(resolve(process.cwd(), 'public', 'robots.txt'), robots)