name: Monorepo CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - refactor-turborepo-monorepo

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  typecheck_lint:
    name: Typecheck + Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps (allow lockfile update)
        run: pnpm install --no-frozen-lockfile

      - name: Typecheck (all)
        run: pnpm turbo run check-types

      - name: Lint (all)
        run: pnpm turbo run lint

  test:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps (allow lockfile update)
        run: pnpm install --no-frozen-lockfile

      - name: Tests (all)
        env:
          CI: "true"
        run: pnpm turbo run test

      - name: Upload coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            **/coverage

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps (allow lockfile update)
        run: pnpm install --no-frozen-lockfile

      - name: Build (all)
        run: pnpm turbo run build

  e2e:
    name: Cypress E2E
    runs-on: ubuntu-24.04
    env:
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
      CYPRESS_INSTALL_BINARY: 14.5.4
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ env.CYPRESS_INSTALL_BINARY }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-${{ env.CYPRESS_INSTALL_BINARY }}-
            cypress-${{ runner.os }}-

      - name: Install deps (root)
        run: pnpm install --frozen-lockfile

      - name: Install Cypress binary (apps/web)
        working-directory: apps/web
        run: npx cypress install

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: apps/web
          browser: electron
          install: false
