name: Monorepo CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - refactor-turborepo-monorepo
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  typecheck_lint:
    name: Typecheck + Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps (allow lockfile update)
        run: pnpm install --no-frozen-lockfile

      - name: Typecheck (all)
        run: pnpm turbo run check-types

      - name: Lint (all)
        run: pnpm turbo run lint

  test:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps (allow lockfile update)
        run: pnpm install --no-frozen-lockfile

      - name: Tests (all)
        env:
          CI: "true"
        run: pnpm turbo run test

      - name: Upload coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            **/coverage

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps (allow lockfile update)
        run: pnpm install --no-frozen-lockfile

      - name: Build (all)
        run: pnpm turbo run build

  e2e:
    name: Cypress E2E (web)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps (allow lockfile update)
        run: pnpm install --no-frozen-lockfile

      - name: Build web app
        run: pnpm --filter ./apps/web run build

      - name: Start web app
        run: pnpm --filter ./apps/web run start -- -p 3000 &

      - name: Wait for http://localhost:3000
        run: npx --yes wait-on@7 http://localhost:3000

      - name: Run Cypress E2E for web
        run: pnpm --filter ./apps/web run test:cypress:e2e
        env:
          CI: "true"
