name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    if: github.repository == 'hsadoqi/final_synapcity'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node 20 + npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Debug environment & files
        run: |
          echo "Commit: $GITHUB_SHA"
          node -v
          npm -v
          echo "== package.json (first 60 lines) =="
          sed -n '1,60p' package.json
          echo "== package-lock.json (first 60 lines) =="
          sed -n '1,60p' package-lock.json || echo "package-lock.json MISSING"
          echo "== hashes =="
          sha256sum package.json package-lock.json || true

      - name: Clean node_modules
        key: ${{ runner.os }}-next-${{ hashFiles('package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-next-

      - name: Ensure lockfile is in sync
        run: |
          npm install --package-lock-only
          git diff --exit-code || (echo "Lockfile is out of sync with package.json. Run 'npm install' locally and commit the updated lockfile." && exit 1)

      - name: Verify lockfile is in sync
        run: npm ci --dry-run

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Run Cypress e2e
        run: npm run test:cypress:e2e
        env:
          CI: "true"
