name: Cypress E2E Tests
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  e2e:
    if: github.repository == 'hsadoqi/final_synapcity'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 1 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Show repo/commit & file hashes
        run: |
          echo "Repo:  $GITHUB_REPOSITORY"
          echo "SHA:   $GITHUB_SHA"
          node -v; npm -v
          sha256sum package.json package-lock.json || true
          (grep -q '"yjs"' package-lock.json && echo "yjs: OK") || echo "yjs: MISSING"
          (grep -q '"lib0"' package-lock.json && echo "lib0: OK") || echo "lib0: MISSING"
          (grep -q '"yaml"' package-lock.json && echo "yaml: OK") || echo "yaml: MISSING"

      - run: rm -rf node_modules

      - name: Try npm install --no-audit --no-fund (fast fail if in sync)
        id: ci_try
        continue-on-error: true
        run: npm install --no-audit --no-fund --no-audit --no-fund

      - name: Fallback: compute lockfile diff (do not commit from CI)
        if: steps.ci_try.outcome == 'failure'
        run: |
          echo "npm install --no-audit --no-fund failed; regenerating lockfile to show diff…"
          rm -rf node_modules
          npm install --no-audit --no-fund
          git diff -- package-lock.json > lockfile.diff || true
          if [ -s lockfile.diff ]; then
            echo "Lockfile changed. Run 'npm install' locally & commit package-lock.json."
            exit 1
          else
            echo "No lockfile change; investigate other causes."
            exit 1
          fi

      - name: Run Cypress e2e
        if: steps.ci_try.outcome == 'success'
        run: npm run test:cypress:e2e
        env: { CI: "true" }

