name: Mirror main to public

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history of main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Show debug refs (optional)
        run: |
          git --version
          git status
          git branch -vv
          git log --oneline -n 3
          git remote -v

      - name: Push HEAD -> Synapcity/synapcity-web main
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/synapcity/synapcity.git
          git push public origin/main:refs/heads/main --force-with-lease
